### ISSUE TITLE
Question about example 2.4

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#25]
Hi, it's me again.:-) Thank you very much for your prompt respond to my last question. I was able to run the example but when I opened the result file with Paraview, it didn't show the arrows like what's on the website. Here's what I got.

<img width="1151" alt="スクリーンショット 2019-03-13 16 44 02" src="https://user-images.githubusercontent.com/25852180/54261791-feec4080-45af-11e9-81d5-19f40e962553.png">

I tried all three readers and they all give the same result. Is this happening because I opened the result file in a wrong way?

**Comment by funsim** [comment]
This is fixed in commit #4b1f6d5. 

Please try again and open the pvd files instead of the xdmf.
