### ISSUE TITLE
Question about data requirement

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#26]
Hi, I am trying to perform a similar experiment as Example 2.3, to simulate tides in a specific area. I read the document and could only figure out that the bathymetric data for the area is required. Is there any other data of the area is required to perform the simulation? Perhaps high and low tide information?

Also, could you explain the 'ranges' and 'constituents' parameter in `Class TidalForcing`?

Sorry for keep interrupting, I really appreciate your help.

**Comment by funsim** [comment]
Hi,

You need to provide:

* a mesh of the domain of interest
* tidal forcing on the open boundaries (you can use the TidalForcing function for this)
* bathymetry information (there are also public and nonpublic databases for this)

There is plenty of online resources explaining "tidal constituents" (see e.g. https://earthscience.stackexchange.com/questions/8407/definitions-of-tidal-harmonic-constituents), I won't repeat it here.

The ranges parameter is an optional parameter to restrict the tidal NetCDF data to the computational domain area. If you are unsure you can just remove this parameter. I copy and pasted the documentation from https://github.com/stephankramer/uptide/blob/master/uptide/tidal_netcdf.py for you:

```        ranges and mask may be specified in a similar way to the NetCDFInterpolator class.
        NOTE: setting a correct coordinate ranges is strongly recommended when reading
        from a NetCDF data base that is significantly bigger than the region of interest,
        as otherwise the tidal signal will be reconstructed for all points of the NetCDF grid
        leading to very slow computations. In parallel the ranges should be set to the coordinate
        range of the local process domain.
```

**Comment by ArnoiZ** [comment]
Hi Simon,

Thank you for your response.

I have two more questions. 
The first is that when providing 'a mesh of the domain of interest', does the file have to be .xml file? 
The second is that does the netCDF bathymetry file have to be exactly the same area as the domain of interest?

Best regards,

Ming
