### ISSUE TITLE
Unable to obtain xxx_facet_id.xml and xxx_physical_region.xml

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#28]
Hi,

Thank you for your update, the conversion script works fine with example data now.

I am trying to create an input mesh of domain of interest. I tried to follow the example procedure(Makefile), but because I don't have a .geo file, I created a mesh file with a cloud of points and skipped the first line of Makefile `gmsh -2 orkney_utm.geo`.

I then tried `dolfin-convert` to convert .msh to .xml, but couldn't get the extra two .xml file.
As a result, when I tried to input the .xml file I created, the program returns an error saying couldn't find the extra two .xml file.

Is there a work around with the input file? Or is there a way I could obtain the extra two .xml file with the .msh file I created? I will attach my .msh file, thank you.

Bests,

Ming
[hiroshima.msh.zip](https://github.com/OpenTidalFarm/OpenTidalFarm/files/3078228/hiroshima.msh.zip)

**Comment by funsim** [comment]
Hi Ming,

The two extra files you are referring to contain the boundary markers (to specify where to apply which boundary conditions), and farm markers (specifying in which areas turbines may be installed). You need to add these information into the .msh files. It's probably best if you compare your .msh files with my .msh files to see what is missing.
