### ISSUE TITLE
Questions about input data

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#29]
Hi,

First question is that does the area of bathymetry data need to be the exact area of the domain of interest?
Also, If I only want to simulate tidal movement, is the information about farm markers still required?

Bests,

Ming

**Comment by funsim** [comment]
Hi Ming,

Yes, the bathyemtry data should cover at least the domain of interest (it can be larger, but it should not be smaller). 
For pure tidal simulations, no farm information is needed.

**Comment by ArnoiZ** [comment]
Hi Simon,

Thank you. One more question, if the area of bathymetry data is larger than the area of the domain of interest, is there anything I need to do(like adding a parameter) to ensure the correct area of bathymetry is used in tidal simulation?

**Comment by funsim** [comment]
No need. OpenTidalFarm expects that the bathymetry is given as a lat/lon NetCDF file, where the depth values stored as “z” field, see [here](https://opentidalfarm.readthedocs.io/en/latest/opentidalfarm.tides.html#opentidalfarm.tidal.BathymetryDepthExpression)

You can find an example code with bathymetry [here](https://opentidalfarm.readthedocs.io/en/latest/opentidalfarm.tides.html)
