### ISSUE TITLE
Newton solver did not converge because maximum number of iterations reached.

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#30]
Hi,

I get this error when performing tidal simulation. 
Last time I asked you about the `range` parameter within `TidalForcing` function, you said I could leave it if I am not sure about it.

Is this error happening because because the `range` parameter is not defined and caused memory overflow? 
If so, is there a way to check the range of my domain of interest?

```
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with NewtonSolver.
*** Reason:  Newton solver did not converge because maximum number of iterations reached.
*** Where:   This error was encountered inside NewtonSolver.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2017.1.0
*** Git changeset:  3d1f687ec9ee39afc0fe6e01800431995b42ad04
*** -------------------------------------------------------------------------
```

**Comment by funsim** [comment]
The error tells you that the non-linear solver could not solve a timestep during the simulation. From this error alone, is difficult to judge where the problem is. I would look at the simulation results up to when the error occurs to see if the tidal forcing  looks reasonable. You could also try to repeat the simulation with a smaller timestep.
