### ISSUE TITLE
Question about tidal boundary forcing in example 2.3

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#31]
Hi,

I am trying to perform tidal simulaition and got a problem when applying tidal boundary forcing, by using the TidalForcing class.
```
eta_expr = TidalForcing(grid_file_name='../data/netcdf/gridES2008.nc',
                        data_file_name='../data/netcdf/hf.ES2008.nc',
                        ranges=((-4.0,0.0), (58.0,61.0)),
                        utm_zone=utm_zone,
                        utm_band=utm_band,
                        initial_time=datetime.datetime(2001, 9, 18, 10, 40),
                        constituents=['Q1', 'O1', 'P1', 'K1', 'N2', 'M2', 'S2', 'K2'], degree=2)
```
I found out that `gridES2008.nc` and `hf.ES2008.nc` are for regional tidal solution for European shelf. So I found the regional tidal solution for [Seas of Okhotsk & Japan ](http://volkov.oce.orst.edu/tides/region.html), but they are in .out file. 

Could opentidalfarm work with it? Or is there a way to convert them to netCDF file?

**Comment by funsim** [comment]
.out is not a standard file format afaik. Maybe ask the authors if they can provide the bathymetry in a .netcdf format, or see if you can find the data structure of the .out file so that you can write your own converter?
