### ISSUE TITLE
Still cannot get the simulation running

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#33]
Hi,

I have fixed the mesh and added a dummy farm marker to generate _physical_region.xml, but the simulation still could not run.
You mentioned that there could be an issue with tidal boundary conditions, do you mean the problem is with the mesh?

Could you tell me what could I try to remedy the issue that newton solver could not converge and which parameters should I set properly to get the simulation going?

**Comment by stephankramer** [comment]
Have you tried with a constant bathymetry (sufficiently deep) as suggested?

**Comment by ArnoiZ** [comment]
Yes, I have set 'z' variable in bathymetry file to constant 100, but it still could out converge.

**Comment by stephankramer** [comment]
Ok, I would suggest simplifying even further then and change to a simple synthetic elevation boundary like in the headland example. This is just a process of elimination to figure out what is going wrong. If that still doesn't work, and you are using a sensible timestep and viscosity, the issue is probably with your mesh indeed.

**Comment by ArnoiZ** [comment]
Hi,

Sorry for the late response, I have drawn a simplified boundary shown below.
![image](https://user-images.githubusercontent.com/25852180/64917021-3e495300-d7c6-11e9-8f83-f0896067e9b2.png)
But the simulation still could not converge. My settings are as follows:
```
prob_params.friction = Constant(0.0025)
# Temporal settings
prob_params.start_time = Constant(0)
prob_params.finish_time = Constant(5*60)
prob_params.dt = Constant(60)
```
Does this means the problem is with the netCDF regional tidal solution?
