### ISSUE TITLE
fenicsproject run: command not found

### ISSUE THREAD

**Issue by dani0303** [OpenTidalFarm/OpenTidalFarm#43]
So I'm helping my friend who is this software for his project however we're having some trouble running it on my virtual machine. I'm currently using Ubuntu via ssh and using docker to run it. I followed the installation steps on the website:
1. Install Docker
2. Install the FEniCS Docker script: curl -s https://get.fenicsproject.org | bash
3. Start an OpenTidalFarm session by running the following command: fenicsproject run quay.io/opentidalfarm/virtual
 Here is where I get the issue when ever i run "fenicsproject run quay.io/opentidalfarm/virtual" I get "fenicsproject: command not found"
I also in the same directory after I ran "curl -s https://get.fenicsproject.org | bash". If you could please help and show how to run one of the examples it would be greatly appreciated?

**Comment by dani0303** [comment]
Btw Ubuntu 20.04

**Comment by pefarrell** [comment]
I think that FEniCS installation script puts the `fenicsproject` command in `$HOME/.local/bin/fenicsproject`. Does running that work? If so, add `$HOME/.local/bin` to your `PATH`.

**Comment by dani0303** [comment]
Thank you for your advice. I ran "sudo /home/ubuntu/.local/bin/fenicsproject run quay.io/opentidalfarm/virtual" but when I ran it I got this write /var/lib/docker/tmp/GetImageBlob328786123: no space left on device.
Does that mean I don't have enough space on my machine?

**Comment by dani0303** [comment]
I'm now running it on my laptop and I think I have it setup. But how do I run an example?

**Comment by dani0303** [comment]
how do I open the file with paraview?

**Comment by dani0303** [comment]
Sorry to be a bother but I still need help. I got everything setup at this point but I'm having trouble visualizing the data in paraview. I keep getting an error and I have tried flushing the data out but nothing works.

"ERROR: In ./VTK/IO/Xdmf2/vtkXdmfReader.cxx, line 488
vtkXdmfReader (0x5638b29b6a10): Failed to read data.

ERROR: In ./VTK/Common/ExecutionModel/vtkExecutive.cxx, line 752
vtkPVCompositeDataPipeline (0x5638b81ae650): Algorithm vtkFileSeriesReader(0x5638b677d0f0) returned failure for request: vtkInformation (0x5638b710f8c0)
  Debug: Off
  Modified Time: 1392615
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0"

If you could please help me get through this piece it would be greatly appreciated.

**Comment by pefarrell** [comment]
I think that paraview error message is saying that it can't read the data. Did the example appear to run correctly? I was never able to get paraview running inside docker, I always transferred the outputs to the machine outside docker and ran paraview there.

**Comment by dani0303** [comment]
The channel simulation ran correctly and I copied the xdmf files using docker ps and ran docker on my host machine. Is there another way I can view the data?

**Comment by dani0303** [comment]
Would it be possible to use metaplotlib in python to show the data if so how I would go about in doing that?

**Comment by pefarrell** [comment]
Hi, I think the best way is to get the .xdmf and .h5 files out of your docker container. I don't know docker very well (I always found it confusing), but the fenicsproject script typically mounts a directory on your actual machine (maybe the current working directory?) to a directory inside the docker container. If you copy the files there inside docker you can run paraview outside docker.

There's some documentation on FEniCS + docker here: https://fenics.readthedocs.io/projects/containers/en/latest/introduction.html#sharing-files-from-the-host-into-the-container

This doesn't appear to be an OpenTidalFarm bug, so I'll close this bug report. If you need further help with FEniCS + docker I suggest trying on the FEniCS slack.
